Repository jemmia-diamond/erpnext, pull requests merged in 2025-06, with the labels that each got.

#29 fix: bug ui and parse data
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#30 feat: show toolbar
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#32 feat: schedule update opportunity
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/opportunity/opportunity.json
  erpnext/crm/doctype/opportunity/opportunity.py
  erpnext/hooks.py
  erpnext/translations/vi.csv
Labels: Review effort 3/5

#33 fix: remove status in list view
  erpnext/selling/doctype/sales_order/sales_order_list.js
Labels: Review effort 1/5

#37 feature: mask phone number in list view
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead_list.js
Labels: Review effort 2/5

#40 feat: update lead ownwer and first reach time
  erpnext/config/config.py
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 2/5

#42 feature: add fetch region based on province on save
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/province/province.json
  erpnext/crm/doctype/province/province.py
  erpnext/patches.txt
  erpnext/seeds/lead/update_region.py
Labels: Review effort 2/5

#41 chore: field name intersted product
  erpnext/crm/doctype/lead/lead_methods.py
Labels: Review effort 1/5

#44 enhance: added fields in serial and promotion for integration
  erpnext/selling/doctype/promotion/promotion.json
  erpnext/selling/doctype/promotion/promotion.py
  erpnext/selling/doctype/serial/serial.json
  erpnext/selling/doctype/serial/serial.py
Labels: Review effort 2/5

#47 feat: create todo lead
  erpnext/config/config.py
  erpnext/crm/doctype/lead/lead_methods.py
Labels: Review effort 2/5

#49 fix: lead source type
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#51 Enhance: link to all relevant contact pancake source
  erpnext/crm/doctype/lead/lead.js
Labels: Review effort 2/5

#53 specify zalo / zalo OA
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#58 feature: play Stringee call record
  erpnext/config/config.py
  erpnext/telephony/doctype/call_log/call_log.js
  erpnext/telephony/doctype/call_log/call_log.py
Labels: Review effort 2/5

#60 fix: lead phone owner
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/lead/lead_methods.py
Labels: Review effort 2/5

#61 feat: hide opportunity lead
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#62 Fix/primary phone
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/lead/lead_methods.py
Labels: Review effort 2/5

#65 feature: add avater in list view
  erpnext/crm/doctype/lead/lead_list.js
Labels: Review effort 2/5

#69 Add zalo koc
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#71 fix: make avatars static
  erpnext/crm/doctype/lead/lead_list.js
Labels: Review effort 1/5

#74 fix: fix sql backfill lead info
  erpnext/crm/doctype/lead/lead_methods.py
Labels: Review effort 2/5
