Repository jemmia-diamond/erpnext, pull requests merged in 2025-10, with the labels that each got.

#139 Feat(sales-order) Backfill Items with Serial Numbers
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/selling/doctype/sales_order_item/sales_order_item.json
  erpnext/selling/doctype/sales_order_item/sales_order_item.py
Labels: Review effort 2/5, Review effort 3/5

#140 feat(sales-order): More Information to Print Invoices
  erpnext/selling/doctype/sales_order/sales_order.js
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/selling/doctype/sales_order_item/sales_order_item.json
  erpnext/selling/doctype/sales_order_item/sales_order_item.py
Labels: Review effort 2/5

#142 Fix(Selling): Change Options in Select Fields
  erpnext/crm/doctype/lead/lead.json
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
Labels: Review effort 2/5

#141 Add field to show attachments
  erpnext/selling/doctype/sales_order/sales_order.json
Labels: Review effort 1/5

#143 Turn on webhook for lead and sale order
  erpnext/crm/doctype/lead/lead.json
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/sales_order/sales_order.json
Labels: Review effort 2/5

#145 fix - set custom to false
  erpnext/crm/doctype/lead/lead.json
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/sales_order/sales_order.json
Labels: Review effort 1/5
