Repository jemmia-diamond/erpnext, pull requests merged in 2025-05, with the labels that each got.

#3 Feature/add lead source
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/lead/lead_methods.py
  erpnext/crm/doctype/lead_channel/lead_channel.json
  erpnext/patches.txt
  erpnext/seeds/item_group/create_default_lead_source.py
Labels: Review effort 3/5

#9 Enhancement: Handle re-order
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/selling/doctype/sales_order_item/sales_order_item.json
  erpnext/selling/doctype/sales_order_reference/__init__.py
  erpnext/selling/doctype/sales_order_reference/sales_order_reference.json
  erpnext/selling/doctype/sales_order_reference/sales_order_reference.py
  erpnext/selling/doctype/sales_team/sales_team.json
Labels: Review effort 3/5

#10 Feature/lead info
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/province/__init__.py
  erpnext/crm/doctype/province/province.json
  erpnext/crm/doctype/province/province.py
  erpnext/crm/doctype/region/__init__.py
  erpnext/crm/doctype/region/region.json
  erpnext/crm/doctype/region/region.py
Labels: Review effort 2/5

#12 Change data type of bank_account field in Customer document
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
Labels: Review effort 2/5

#15 Change field in migrate pancake data
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 1/5

#13 Enhance Sales Order and Customer for integration
  erpnext/selling/doctype/customer/customer.js
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/doctype/product_category/__init__.py
  erpnext/selling/doctype/product_category/product_category.json
  erpnext/selling/doctype/product_category/product_category.py
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/selling/doctype/sales_order_product_category/__init__.py
  erpnext/selling/doctype/sales_order_product_category/sales_order_product_category.json
  erpnext/selling/doctype/sales_order_product_category/sales_order_product_category.py
Labels: Review effort 3/5

#17 remove bug re-order workflow
  erpnext/selling/doctype/sales_order/sales_order.py
Labels: Review effort 1/5

#16 Refactor Lead Management
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/lead_channel/__init__.py
  erpnext/crm/doctype/lead_channel/lead_channel.json
  erpnext/crm/doctype/lead_channel/lead_channel.py
  erpnext/crm/doctype/lead_source/lead_source.json
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
Labels: Review effort 2/5

#23 Feature/latest message
  erpnext/crm/doctype/lead/lead.py
  erpnext/crm/doctype/lead/lead_methods.py
Labels: Review effort 2/5

#19 feat: lead feedback
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
  erpnext/selling/doctype/customer/customer.json
  erpnext/translations/vi.csv
Labels: Review effort 2/5

#26 Feature/sales order UI
  erpnext/selling/doctype/sales_order/sales_order.js
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order_list.js
Labels: Review effort 3/5
