Repository jemmia-diamond/erpnext, pull requests merged in 2025-07, with the labels that each got.

#75 Remove AIHUB integration
  erpnext/config/config.py
  erpnext/crm/doctype/lead/lead_dao.py
  erpnext/crm/doctype/lead/lead_methods.py
  erpnext/hooks.py
  erpnext/packages/ai_hub/ai_hub.py
  erpnext/packages/ai_hub/ai_hub_connector.py
Labels: Review effort 2/5

#77 Solve empty phone in list
  erpnext/patches.txt
  erpnext/seeds/lead/clear_empty_phone.py
Labels: Review effort 1/5

#79 enhance: lead phone to be unique
  erpnext/crm/doctype/lead/lead.json
Labels: Review effort 1/5

#80 refactor: simplify contact creation logic in lead processing
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 2/5

#81 fix: streamline contact link retrieval in lead after insert
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 2/5

#83 refactor: find contact by one request
  erpnext/crm/doctype/lead/lead_list.js
Labels: Review effort 2/5

#90 auto create new preferred product
  erpnext/crm/doctype/lead/lead_methods.py
  erpnext/crm/doctype/lead_product/lead_product_dao.py
Labels: Review effort 2/5

#91 auto update the revenue after insert order
  erpnext/patches.txt
  erpnext/seeds/customer/update_revenue.py
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/doctype/sales_order/sales_order.py
Labels: Review effort 2/5

#92 Update lead_owner
  erpnext/crm/doctype/lead/lead.py
Labels: Review effort 2/5

#93 feature: map customer and lead by phone
  erpnext/hooks.py
  erpnext/selling/doctype/customer/customer_methods.py
Labels: Review effort 2/5

#94 add referral value
  erpnext/hooks.py
  erpnext/selling/doctype/customer/customer.py
Labels: Review effort 2/5, Possible security concern

#97 change logic of cashback
  erpnext/selling/doctype/customer/customer.py
Labels: Review effort 2/5

#100 Selling/coupon
  erpnext/config/config.py
  erpnext/hooks.py
  erpnext/selling/doctype/coupon/__init__.py
  erpnext/selling/doctype/coupon/coupon.json
  erpnext/selling/doctype/coupon/coupon.py
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
Labels: Review effort 4/5, Possible security concern

#102 Feature/custom opportunity
  erpnext/crm/doctype/lead/lead.js
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/opportunity/opportunity.json
  erpnext/crm/doctype/opportunity/opportunity.py
  erpnext/hooks.py
Labels: Review effort 3/5

#104 Fix: Change Logic Save Opportunity Date
  erpnext/crm/doctype/opportunity/opportunity.json
  erpnext/crm/doctype/opportunity/opportunity.py
Labels: Review effort 2/5

#105 add coupon type
  erpnext/selling/doctype/coupon/coupon.json
  erpnext/selling/doctype/coupon/coupon.py
Labels: Review effort 3/5

#106 Setup: make lead changes always be tracked
  erpnext/crm/doctype/lead/lead.json
Labels: Review effort 1/5

#101 Feature: create sales order notification
  erpnext/config/config.py
  erpnext/selling/doctype/sales_order/sales_order.js
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
Labels: Review effort 3/5, Possible security concern

#107 Disable todo actions in lead form view
  erpnext/public/js/utils/crm_activities.js
Labels: Review effort 2/5

#108 Feature/sales order settings
  erpnext/selling/doctype/policy/__init__.py
  erpnext/selling/doctype/policy/policy.json
  erpnext/selling/doctype/policy/policy.py
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/selling/doctype/sales_order_policy/__init__.py
  erpnext/selling/doctype/sales_order_policy/sales_order_policy.json
  erpnext/selling/doctype/sales_order_policy/sales_order_policy.py
Labels: Review effort 2/5
